### ISSUE TITLE
not working after reboot

### ISSUE THREAD

**Issue by ktulu84** [dobragab/Mi5CameraCalibrate#1]
the app is working good, but calibration doesn't work at boot time, I have to manually start after every reboot

EDIT: here it is the error in logcat
01-13 17:03:42.904  1172  2526 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.BOOT_COMPLETED flg=0x9000010 (has extras) } to dobragab.sch.bme.hu.cit2/.BootReceiver requires android.permission.RECEIVE_BOOT_COMPLETED due to sender null (uid 1000)

EDIT 2: added the above permission in manifest, now it works good on boot. I suggest you to add the following code in the onClick() method, the app need to be start only once, then the icon can be hidden

`PackageManager p = getPackageManager();
p.setComponentEnabledSetting(getComponentName(), PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);`

**Comment by dobragab** [comment]
Thanks for the edit, will be easy to fix with that information. Sorry for the mistake anyway :)

**Comment by ktulu84** [comment]
i edited it again, i tried the above modifications and the app works very good, thanks to you for the project :D

**Comment by dobragab** [comment]
Thanks!

I'm planning to do a shallow version without Activity, that can be included in roms, and works without the user needing to know.
