### ISSUE TITLE
shallow version not working.

### ISSUE THREAD

**Issue by ktulu84** [dobragab/Mi5CameraCalibrate#2]
it seems that it is necessary to start the app at least once to make it work:

"Applications are in a stopped state when they are first installed but are not yet launched and when they are manually stopped by the user (in Manage Applications)."

[https://developer.android.com/about/versions/android-3.1.html](url)

**Comment by dobragab** [comment]
Updated [v0.2s](https://github.com/dobragab/Mi5CameraCalibrate/releases/tag/v0.2s). It is now available as a flashable zip, works for me properly. Please confirm if it works for you as well.

**Comment by ktulu84** [comment]
confirmed!
